### ISSUE TITLE
Home Assistant Energy Integration

### ISSUE THREAD

**Issue by forgenator** [carohauta/oma-helen-ha-integration#16]
Hi, i have helen exchange contract, and all works just fine. But i noticed that all energy data is downloaded for the wrong days. In home assistant, it shows yesterdays energy consumption as todays energy consumption.

**Comment by mikenhu** [comment]
Hi I also found the same issue. The whole day energy consumption yesterday is shown up as an hour of consumption today, for example. My contract is fixed price btw. Also the cost is not taken into the calculation.

**Comment by carohauta** [comment]
Hi!

This is by design. The integration only supports daily resolution in the Energy Dashboard. At the moment there are no plans to make it support hourly resolution. 

In order to be able to display hourly data points, the Energy Dashboard should support updating data points in the past because Helen usually has at least 24 hour delay in their new data. AFAIK at the moment there is no official support for importing historical data to the Energy Dashboard in Home Assistant.

The reason why one whole day's consumption is shown in one hourly bar in the diagram is because the integration polls the API every three hours and when the data has been refreshed, the state of the integration will be updated.
