### ISSUE TITLE
Using HA energy dashboard, first day of month has zero consumption

### ISSUE THREAD

**Issue by lakofsth** [carohauta/oma-helen-ha-integration#4]
My guess without looking at code is that we'd be requesting the previous day of the month from the API on the first day of the month.

**Comment by carohauta** [comment]
The Helen API data is lagging behind for about one day – sometimes even two days. This also means that the HA integration data is lagging behind and is noticeable especially in the beginning of each month when it might show zero usage for the first day or two. You might notice that the `last month total usage` will update accordingly in this case.

Because the Helen API data usually updates only once per day, I configured the HA integration itself to update only once every six hours. This of course could in some cases create additional six hours delay on top.

**Comment by lakofsth** [comment]
Thanks for getting back to me. I am not sure how to go about integrating
the last month usage data into the HA energy dashboard. It seems to want a
single source for supplier information. So I suppose I had thought that a
logical solution on the first day of the month would be to request the last
day of the previous month - since every day in the HA dashboard is
effectively reflecting the previous day's usage.

**Comment by lakofsth** [comment]
Maybe simplest to close this
